from time import sleep
l = input('Está preparado para a recapitulação?')
sleep(2)
print('Bom, aprendi os seguintes comandos')
sleep(2)
print('print(''.format())')
sleep(2)
print('tipos primitivos')
sleep(2)
print('str==string, floot==numeros flutuantes tipo 2.5, boat==espaco vazio ou cheio e int==numeros inteiros')
sleep(2)
print('comandos como type() verifica o tipo primitivo e .is, mostra na tela com  comando print')
sleep(2)
print('comandos basicos')
sleep(2)
print('(,)==junta e (=) == recebe (==) == igual (#) == comentario')
sleep(2)
print('Expressões Aritmetica')
sleep(2)
print('é necessario sempre respeitar a ordem da aritmetica')
sleep(2)
print('resolvendo primeiro na ordem a seguir')
sleep(2)
print('()(conchetes 1 )')
sleep(2)
print('**(potencia 2 )')
sleep(2)
print('*, / , // , % (multiplicação, divisão, divisão inteiro e a sobra da divisão 3)')
sleep(2)
print('+ , _ (soma e diminuir 4)')
sleep(2)
print('Vou fazer uma simples calculadora da tabuada do 9 com potencias e sobras na ordem')
sleep(2)
n = int(input('digite qualquer numero para a tabuada do nove'))
sleep(2)
a = n**9
b = 9*n
c = 9/n
d = 9//n
f = 9%n
g = 9+n
h = n-9
print('a potencia de 9 elevado a {} deu {}'.format(n,a))
sleep(2)
print ('a multiplicação de 9 vezes {} deu {}'.format(n,b))
sleep(2)
print('A divisão de 9 por {} deu {}'.format(n,c))
sleep(2)
print('A divisão inteira de 9 por {} deu {} e sobrou {}'.format(n,d,f))
sleep(2)
print('A soma de 9 e {} deu {}'.format(n,g))
sleep(2)
print('A diminuição de 9 por {} deu {}'.format(n,h))
sleep(2)
